apiVersion: v1
kind: PersistentVolume
metadata:
  name: geo-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/volumes/geo-pv
    type: DirectoryOrCreate
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - h3.hotelbench.meshbench-pg0.clemson.cloudlab.us
  storageClassName: geo-storage
  volumeMode: Filesystem
