apiVersion: v1
kind: PersistentVolume
metadata:
  name: TODO-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/appnet
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: TODO-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
